# Generated by Django 5.1.5 on 2025-09-12 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_news_sources', models.BooleanField(default=False)),
                ('can_create_businesses', models.BooleanField(default=True)),
                ('city_access', models.CharField(blank=True, help_text='Ciudades que puede administrar (separadas por comas)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario administrador',
                'verbose_name_plural': 'Usuarios administradores',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del negocio')),
                ('business_type', models.CharField(choices=[('coffee_shop', 'Cafetería'), ('restaurant', 'Restaurante'), ('pub', 'Pub/Bar'), ('bookstore', 'Librería')], max_length=50, verbose_name='Tipo de negocio')),
                ('city', models.CharField(choices=[('medellin', 'Medellín'), ('bogota', 'Bogotá'), ('cartagena', 'Cartagena'), ('barranquilla', 'Barranquilla')], max_length=50, verbose_name='Ciudad')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descripción del negocio')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('target_audience', models.CharField(blank=True, help_text='Ej: Estudiantes universitarios, profesionales, familias', max_length=200, verbose_name='Público objetivo')),
                ('operating_hours_start', models.TimeField(blank=True, null=True, verbose_name='Hora de apertura')),
                ('operating_hours_end', models.TimeField(blank=True, null=True, verbose_name='Hora de cierre')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad máxima')),
                ('staff_count', models.PositiveIntegerField(default=1, verbose_name='Número de empleados')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Recibir notificaciones por email')),
                ('recommendation_frequency', models.CharField(choices=[('real_time', 'Tiempo real'), ('daily', 'Diario'), ('weekly', 'Semanal')], default='daily', max_length=20, verbose_name='Frecuencia de recomendaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Palabra clave')),
                ('weight', models.FloatField(default=1.0, help_text='Importancia de esta palabra clave (0.1 - 2.0)', verbose_name='Peso')),
                ('is_negative', models.BooleanField(default=False, help_text='Excluir noticias que contengan esta palabra', verbose_name='Es negativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Palabra clave del negocio',
                'verbose_name_plural': 'Palabras clave del negocio',
                'unique_together': {('business', 'keyword')},
            },
        ),
    ]
