# Generated by Django 5.1.5 on 2025-10-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='geographic_radius_km',
            field=models.FloatField(default=5.0, help_text='Mostrar noticias dentro de este radio (kilómetros)', verbose_name='Radio geográfico (km)'),
        ),
        migrations.AddField(
            model_name='business',
            name='include_citywide_events',
            field=models.BooleanField(default=True, help_text='Mostrar eventos grandes que afectan toda la ciudad', verbose_name='Incluir eventos a nivel ciudad'),
        ),
        migrations.AddField(
            model_name='business',
            name='include_national_events',
            field=models.BooleanField(default=False, help_text='Mostrar eventos masivos de nivel nacional (Copa América, etc.)', verbose_name='Incluir eventos nacionales'),
        ),
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Coordenada geográfica para matching basado en distancia', null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Coordenada geográfica para matching basado en distancia', null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.CharField(blank=True, help_text='Barrio específico (El Poblado, Laureles, Chapinero, etc.)', max_length=100, verbose_name='Barrio/Localidad'),
        ),
    ]
