# Generated by Django 5.1.5 on 2025-10-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_add_geographic_matching_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='has_tv_screens',
            field=models.BooleanField(default=False, help_text='Negocio tiene TVs para ver eventos deportivos/culturales (aumenta relevancia de eventos remotos)', verbose_name='Tiene pantallas/TV'),
        ),
    ]
