# Generated by Django 5.1.5 on 2025-10-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_seed_businesstype_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Identificador único (pub, restaurant, coffee_shop, bookstore)', max_length=50, unique=True, verbose_name='Código')),
                ('display_name', models.CharField(max_length=100, verbose_name='Nombre (English)')),
                ('display_name_es', models.CharField(max_length=100, verbose_name='Nombre (Español)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fa-beer, fa-utensils)', max_length=50, verbose_name='Icono')),
                ('suitability_weight', models.FloatField(default=0.3, help_text='Peso del business_suitability_score (0.0-1.0)', verbose_name='Peso de idoneidad')),
                ('keyword_weight', models.FloatField(default=0.2, help_text='Peso del matching de keywords (0.0-1.0)', verbose_name='Peso de palabras clave')),
                ('event_scale_weight', models.FloatField(default=0.2, help_text='Peso de la escala del evento (0.0-1.0)', verbose_name='Peso de escala de evento')),
                ('neighborhood_weight', models.FloatField(default=0.3, help_text='Peso de cercanía geográfica (0.0-1.0)', verbose_name='Peso de proximidad')),
                ('min_relevance_threshold', models.FloatField(default=0.5, help_text='Mínimo relevance_score para mostrar artículo (0.0-1.0)', verbose_name='Umbral mínimo de relevancia')),
                ('min_suitability_threshold', models.FloatField(default=0.5, help_text='Mínimo business_suitability_score para procesar (0.0-1.0)', verbose_name='Umbral mínimo de idoneidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de negocio',
                'verbose_name_plural': 'Tipos de negocio',
                'ordering': ['display_name'],
            },
        ),
    ]
