# Generated by Django 5.1.5 on 2025-10-28 15:48

from django.db import migrations


def seed_business_types(apps, schema_editor):
    """Seed initial 4 business types"""
    BusinessType = apps.get_model('businesses', 'BusinessType')

    business_types_data = [
        {
            'code': 'pub',
            'display_name': 'Pub/Bar',
            'display_name_es': 'Pub/Bar',
            'description': 'Bar, pub o taberna que sirve bebidas y entretenimiento',
            'icon': 'fa-beer',
            'suitability_weight': 0.3,
            'keyword_weight': 0.2,
            'event_scale_weight': 0.2,
            'neighborhood_weight': 0.3,
            'min_relevance_threshold': 0.5,
            'min_suitability_threshold': 0.5,
            'is_active': True
        },
        {
            'code': 'restaurant',
            'display_name': 'Restaurant',
            'display_name_es': 'Restaurante',
            'description': 'Restaurante que sirve comida',
            'icon': 'fa-utensils',
            'suitability_weight': 0.3,
            'keyword_weight': 0.2,
            'event_scale_weight': 0.2,
            'neighborhood_weight': 0.3,
            'min_relevance_threshold': 0.5,
            'min_suitability_threshold': 0.5,
            'is_active': True
        },
        {
            'code': 'coffee_shop',
            'display_name': 'Coffee Shop',
            'display_name_es': 'Cafetería',
            'description': 'Cafetería o café',
            'icon': 'fa-coffee',
            'suitability_weight': 0.3,
            'keyword_weight': 0.2,
            'event_scale_weight': 0.2,
            'neighborhood_weight': 0.3,
            'min_relevance_threshold': 0.5,
            'min_suitability_threshold': 0.5,
            'is_active': True
        },
        {
            'code': 'bookstore',
            'display_name': 'Bookstore',
            'display_name_es': 'Librería',
            'description': 'Librería que vende libros y artículos relacionados',
            'icon': 'fa-book',
            'suitability_weight': 0.3,
            'keyword_weight': 0.2,
            'event_scale_weight': 0.2,
            'neighborhood_weight': 0.3,
            'min_relevance_threshold': 0.5,
            'min_suitability_threshold': 0.5,
            'is_active': True
        }
    ]

    for data in business_types_data:
        BusinessType.objects.get_or_create(
            code=data['code'],
            defaults=data
        )


def reverse_seed_business_types(apps, schema_editor):
    """Remove seeded business types"""
    BusinessType = apps.get_model('businesses', 'BusinessType')
    BusinessType.objects.filter(
        code__in=['pub', 'restaurant', 'coffee_shop', 'bookstore']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_businesstype'),
    ]

    operations = [
        migrations.RunPython(seed_business_types, reverse_seed_business_types),
    ]
