# Generated by Django 5.1.5 on 2025-10-28 15:49

from django.db import migrations, models
import django.db.models.deletion


def migrate_business_type_data(apps, schema_editor):
    """
    Map existing CharField business_type values to new FK
    """
    Business = apps.get_model('businesses', 'Business')
    BusinessType = apps.get_model('businesses', 'BusinessType')

    # Mapping of old string values to new codes
    type_mapping = {
        'bar': 'pub',  # Map bar → pub
        'pub': 'pub',
        'restaurant': 'restaurant',
        'coffee_shop': 'coffee_shop',
        'bookstore': 'bookstore'
    }

    for business in Business.objects.all():
        old_type = business.business_type

        # Get the new code (with fallback)
        new_code = type_mapping.get(old_type, old_type)

        try:
            new_type = BusinessType.objects.get(code=new_code)
            business.business_type_fk = new_type
            business.save(update_fields=['business_type_fk'])
            print(f"Migrated {business.name}: {old_type} → {new_code}")
        except BusinessType.DoesNotExist:
            print(f"WARNING: Could not find BusinessType for code '{new_code}' (original: '{old_type}')")
            # Leave business_type_fk as NULL - admin will need to fix manually


def reverse_migration(apps, schema_editor):
    """No reverse migration needed - data stays in old field"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_seed_business_types'),
    ]

    operations = [
        # Step 1: Add new nullable FK field
        migrations.AddField(
            model_name='business',
            name='business_type_fk',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',  # No reverse relation yet
                to='businesses.businesstype',
                verbose_name='Tipo de negocio (nuevo)'
            ),
        ),
        # Step 2: Migrate data from old field to new field
        migrations.RunPython(migrate_business_type_data, reverse_migration),
    ]
