# Generated by Django 5.1.5 on 2025-10-28 16:00

import django.db.models.deletion
from django.db import migrations, models


def migrate_business_type_keyword_data(apps, schema_editor):
    """Migrate BusinessTypeKeyword.business_type from CharField to FK"""
    BusinessTypeKeyword = apps.get_model('businesses', 'BusinessTypeKeyword')
    BusinessType = apps.get_model('businesses', 'BusinessType')

    for btk in BusinessTypeKeyword.objects.all():
        old_type = btk.business_type  # String value
        try:
            new_type = BusinessType.objects.get(code=old_type)
            btk.business_type_fk = new_type
            btk.save(update_fields=['business_type_fk'])
        except BusinessType.DoesNotExist:
            print(f"WARNING: Could not find BusinessType for code '{old_type}'")


def reverse_migration(apps, schema_editor):
    """No-op reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_migrate_business_type_to_fk_step1'),
    ]

    operations = [
        # PART 1: Complete Business.business_type migration
        # -------------------------------------------------
        # Step 1.1: Remove old CharField
        migrations.RemoveField(
            model_name='business',
            name='business_type',
        ),
        # Step 1.2: Rename FK field
        migrations.RenameField(
            model_name='business',
            old_name='business_type_fk',
            new_name='business_type',
        ),
        # Step 1.3: Update FK attributes
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='businesses',
                to='businesses.businesstype',
                verbose_name='Tipo de negocio'
            ),
        ),

        # PART 2: Migrate BusinessTypeKeyword.business_type
        # -------------------------------------------------
        # Step 2.1: Add nullable FK field
        migrations.AddField(
            model_name='businesstypekeyword',
            name='business_type_fk',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='businesses.businesstype',
                verbose_name='Tipo de negocio (nuevo)'
            ),
        ),
        # Step 2.2: Migrate data
        migrations.RunPython(migrate_business_type_keyword_data, reverse_migration),
        # Step 2.3: Remove old CharField
        migrations.RemoveField(
            model_name='businesstypekeyword',
            name='business_type',
        ),
        # Step 2.4: Rename FK field
        migrations.RenameField(
            model_name='businesstypekeyword',
            old_name='business_type_fk',
            new_name='business_type',
        ),
        # Step 2.5: Make FK non-nullable and update attributes
        migrations.AlterField(
            model_name='businesstypekeyword',
            name='business_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='keywords',
                to='businesses.businesstype',
                verbose_name='Tipo de negocio'
            ),
        ),
    ]
