project_name: "NaviGate"
statuses: ["Backlog", "To Do", "In Progress", "Review", "Done"]
labels: []
milestones: []
date_format: yyyy-mm-dd
max_column_width: 80
auto_open_browser: true
default_port: 6420
remote_operations: false
auto_commit: false
bypass_git_hooks: false
check_active_branches: false
active_branch_days: 30
