# Generated by Django 5.1.5 on 2025-09-12 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('category', models.CharField(choices=[('inventory', 'Inventario'), ('staffing', 'Personal'), ('marketing', 'Marketing'), ('pricing', 'Precios'), ('operations', 'Operaciones'), ('partnerships', 'Alianzas'), ('events', 'Eventos'), ('seasonal', 'Estacional')], max_length=20, verbose_name='Categoría')),
                ('action_type', models.CharField(choices=[('increase_inventory', 'Aumentar inventario'), ('hire_staff', 'Contratar personal'), ('create_promotion', 'Crear promoción'), ('adjust_hours', 'Ajustar horarios'), ('contact_supplier', 'Contactar proveedor'), ('plan_event', 'Planificar evento'), ('social_campaign', 'Campaña en redes sociales'), ('partner_collaboration', 'Colaboración con socios'), ('price_adjustment', 'Ajuste de precios'), ('menu_modification', 'Modificar menú/ofertas')], max_length=30, verbose_name='Tipo de acción')),
                ('title_template', models.CharField(help_text='Use {variables} para datos dinámicos', max_length=300, verbose_name='Plantilla de título')),
                ('description_template', models.TextField(verbose_name='Plantilla de descripción')),
                ('reasoning_template', models.TextField(blank=True, verbose_name='Plantilla de razonamiento')),
                ('default_priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad por defecto')),
                ('default_effort_score', models.FloatField(default=0.5, verbose_name='Puntuación de esfuerzo por defecto')),
                ('applicable_business_types', models.JSONField(default=list, verbose_name='Tipos de negocio aplicables')),
                ('required_keywords', models.JSONField(default=list, verbose_name='Palabras clave requeridas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de recomendación',
                'verbose_name_plural': 'Plantillas de recomendaciones',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('inventory', 'Inventario'), ('staffing', 'Personal'), ('marketing', 'Marketing'), ('pricing', 'Precios'), ('operations', 'Operaciones'), ('partnerships', 'Alianzas'), ('events', 'Eventos'), ('seasonal', 'Estacional')], max_length=20, verbose_name='Categoría')),
                ('action_type', models.CharField(choices=[('increase_inventory', 'Aumentar inventario'), ('hire_staff', 'Contratar personal'), ('create_promotion', 'Crear promoción'), ('adjust_hours', 'Ajustar horarios'), ('contact_supplier', 'Contactar proveedor'), ('plan_event', 'Planificar evento'), ('social_campaign', 'Campaña en redes sociales'), ('partner_collaboration', 'Colaboración con socios'), ('price_adjustment', 'Ajuste de precios'), ('menu_modification', 'Modificar menú/ofertas')], max_length=30, verbose_name='Tipo de acción')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], max_length=10, verbose_name='Prioridad')),
                ('confidence_score', models.FloatField(help_text='0.0 - 1.0, generado por ML', verbose_name='Puntuación de confianza')),
                ('impact_score', models.FloatField(help_text='0.0 - 1.0, impacto potencial en el negocio', verbose_name='Puntuación de impacto')),
                ('effort_score', models.FloatField(default=0.5, help_text='0.0 - 1.0, esfuerzo requerido para implementar', verbose_name='Puntuación de esfuerzo')),
                ('recommended_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha recomendada de inicio')),
                ('recommended_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha recomendada de fin')),
                ('estimated_duration_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración estimada (horas)')),
                ('reasoning', models.TextField(blank=True, help_text='Por qué se genera esta recomendación', verbose_name='Razonamiento')),
                ('resources_needed', models.JSONField(blank=True, default=list, help_text='Lista de recursos, personal, materiales, etc.', verbose_name='Recursos necesarios')),
                ('expected_outcomes', models.TextField(blank=True, verbose_name='Resultados esperados')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Visto')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Aceptado')),
                ('is_implemented', models.BooleanField(default=False, verbose_name='Implementado')),
                ('user_feedback', models.TextField(blank=True, verbose_name='Comentarios del usuario')),
                ('user_rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calificación del usuario (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira el')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='businesses.business')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Recomendación',
                'verbose_name_plural': 'Recomendaciones',
                'ordering': ['-priority', '-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('helpful', 'Útil'), ('not_helpful', 'No útil'), ('implemented', 'Implementado'), ('not_relevant', 'No relevante'), ('too_late', 'Muy tarde'), ('too_early', 'Muy temprano')], max_length=20, verbose_name='Tipo de comentario')),
                ('rating', models.PositiveIntegerField(help_text='1 = Muy malo, 5 = Excelente', verbose_name='Calificación (1-5)')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios adicionales')),
                ('implemented_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de implementación')),
                ('implementation_notes', models.TextField(blank=True, verbose_name='Notas de implementación')),
                ('actual_outcomes', models.TextField(blank=True, verbose_name='Resultados reales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommendations.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario sobre recomendación',
                'verbose_name_plural': 'Comentarios sobre recomendaciones',
            },
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['business', 'priority'], name='recommendat_busines_882c22_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['confidence_score'], name='recommendat_confide_fd7ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['is_viewed', 'is_accepted'], name='recommendat_is_view_b952de_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['created_at'], name='recommendat_created_0cbb1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendationfeedback',
            unique_together={('recommendation', 'user')},
        ),
    ]
