# Generated by Django 5.1.5 on 2025-10-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_taxonomy', '0003_add_broadcastability_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identificador del tipo de cocina (ej: italian, japanese, colombian)', max_length=50, unique=True, verbose_name='Código')),
                ('name_es', models.CharField(help_text='Nombre en español (ej: Italiana, Japonesa)', max_length=100, verbose_name='Nombre (Español)')),
                ('name_en', models.CharField(help_text='Nombre en inglés (ej: Italian, Japanese)', max_length=100, verbose_name='Nombre (Inglés)')),
                ('description', models.TextField(blank=True, help_text='Descripción del tipo de cocina', verbose_name='Descripción')),
                ('keywords', models.JSONField(default=list, help_text='Keywords para detección: ["italiano", "pasta", "pizza", "risotto"]', verbose_name='Palabras clave')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desactivado, no se usará en extracción', verbose_name='Activo')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cocina',
                'verbose_name_plural': 'Tipos de Cocina',
                'ordering': ['display_order', 'name_es'],
            },
        ),
    ]
