# Generated by Django 5.1.5 on 2025-10-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newssource_options_remove_newssource_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='crawl_retry_after',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora cuando se puede intentar rastrear nuevamente', null=True, verbose_name='Reintentar después de'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='crawl_status',
            field=models.CharField(choices=[('unknown', 'No probado'), ('rss_available', 'RSS disponible'), ('manual_crawlable', 'Crawling manual funciona'), ('spa_detected', 'SPA/JavaScript detectado'), ('uncrawlable', 'No se puede rastrear')], default='unknown', help_text='Indica si el sitio puede ser rastreado y cómo', max_length=20, verbose_name='Estado de rastreo'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='failed_crawl_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Conteo de fallos consecutivos'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='last_crawl_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último intento de rastreo'),
        ),
    ]
