# Generated by Django 5.1.5 on 2025-10-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newssource_crawl_retry_after_newssource_crawl_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(blank=True, choices=[('eventos', 'Eventos'), ('gastronomia', 'Gastronomía'), ('infraestructura', 'Infraestructura'), ('clima-alertas', 'Clima y Alertas'), ('turismo', 'Turismo'), ('economia', 'Economía'), ('regulaciones', 'Regulaciones'), ('educacion', 'Educación'), ('comunidad', 'Comunidad'), ('seguridad', 'Seguridad')], help_text='Categoría principal visible para el usuario', max_length=30, null=True, verbose_name='Categoría pública'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('conciertos', 'Conciertos'), ('festivales', 'Festivales'), ('deportes', 'Deportes'), ('teatro-cultura', 'Teatro y Cultura'), ('ferias', 'Ferias'), ('tendencias-gastronomicas', 'Tendencias Gastronómicas'), ('bebidas', 'Bebidas'), ('competencias-culinarias', 'Competencias Culinarias'), ('apertura-cierre', 'Apertura/Cierre'), ('productos-nuevos', 'Productos Nuevos'), ('obras-viales', 'Obras Viales'), ('transporte-publico', 'Transporte Público'), ('desarrollo-urbano', 'Desarrollo Urbano'), ('servicios-publicos', 'Servicios Públicos'), ('clima-extremo', 'Clima Extremo'), ('alertas-emergencia', 'Alertas de Emergencia'), ('desastres-naturales', 'Desastres Naturales'), ('estadisticas-turismo', 'Estadísticas de Turismo'), ('feriados-puentes', 'Feriados y Puentes'), ('temporada-alta-baja', 'Temporada Alta/Baja'), ('turismo-internacional', 'Turismo Internacional'), ('tendencias-consumo', 'Tendencias de Consumo'), ('inflacion-precios', 'Inflación y Precios'), ('empleo', 'Empleo'), ('poder-adquisitivo', 'Poder Adquisitivo'), ('leyes-nuevas', 'Leyes Nuevas'), ('permisos-licencias', 'Permisos y Licencias'), ('salud-publica', 'Salud Pública'), ('impuestos', 'Impuestos'), ('horarios-restricciones', 'Horarios y Restricciones'), ('universidades', 'Universidades'), ('colegios', 'Colegios'), ('inicio-fin-semestre', 'Inicio/Fin de Semestre'), ('eventos-barriales', 'Eventos Barriales'), ('mercados-ferias', 'Mercados y Ferias'), ('tendencias-sociales', 'Tendencias Sociales'), ('celebraciones-locales', 'Celebraciones Locales'), ('seguridad-publica', 'Seguridad Pública'), ('zonas-riesgo', 'Zonas de Riesgo'), ('operativos-policiales', 'Operativos Policiales')], help_text='Subcategoría detallada para clasificación ML', max_length=50, null=True, verbose_name='Subcategoría privada'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='event_type',
            field=models.CharField(blank=True, choices=[('sports', 'Deportes'), ('cultural', 'Cultural'), ('gastronomy', 'Gastronomía'), ('education', 'Educación'), ('business', 'Negocios'), ('entertainment', 'Entretenimiento'), ('tourism', 'Turismo'), ('construction', 'Construcción'), ('transportation', 'Transporte'), ('weather', 'Clima'), ('government', 'Gobierno'), ('other', 'Otro')], max_length=20, null=True, verbose_name='Tipo de evento detectado (legacy)'),
        ),
    ]
