# Generated by Django 5.1.5 on 2025-10-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsarticle_category_newsarticle_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='business_suitability_score',
            field=models.FloatField(default=0.0, help_text='0.0-1.0: Qué tan relevante es para CUALQUIER negocio de hostelería', verbose_name='Puntuación de idoneidad para negocios'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='event_duration_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Duración del evento (horas)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='event_end_datetime',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora específica de fin', null=True, verbose_name='Fecha/hora de fin del evento'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='event_scale',
            field=models.CharField(blank=True, choices=[('small', 'Pequeño (<500)'), ('medium', 'Mediano (500-5000)'), ('large', 'Grande (5000-50000)'), ('massive', 'Masivo (>50000)')], max_length=20, verbose_name='Escala del evento'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='event_start_datetime',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora específica de inicio', null=True, verbose_name='Fecha/hora de inicio del evento'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='event_subtype',
            field=models.CharField(blank=True, help_text='football match, rock concert, food festival, etc.', max_length=100, verbose_name='Subtipo de evento'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='event_type_detected',
            field=models.CharField(blank=True, help_text='sports_match, concert, festival, marathon, conference, etc.', max_length=50, verbose_name='Tipo de evento detectado (ML)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='expected_attendance',
            field=models.IntegerField(blank=True, help_text='Número estimado de asistentes', null=True, verbose_name='Asistencia esperada'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='feature_extraction_confidence',
            field=models.FloatField(default=0.0, help_text='0.0-1.0: Nivel de confianza en las features extraídas', verbose_name='Confianza de extracción'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='feature_extraction_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de extracción de features'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='features_extracted',
            field=models.BooleanField(default=False, help_text='Indica si las features ML ya fueron extraídas', verbose_name='Features extraídas'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Coordenada geográfica', null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Coordenada geográfica', null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='neighborhood',
            field=models.CharField(blank=True, help_text='Barrio específico (El Poblado, Laureles, etc.)', max_length=100, verbose_name='Barrio/Localidad'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='primary_city',
            field=models.CharField(blank=True, help_text='Ciudad donde ocurre el evento o noticia', max_length=100, verbose_name='Ciudad principal'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='urgency_score',
            field=models.FloatField(default=0.0, help_text='0.0-1.0: Qué tan urgente es actuar sobre esta noticia', verbose_name='Puntuación de urgencia'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='venue_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección del lugar'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='venue_name',
            field=models.CharField(blank=True, help_text='Nombre del venue/estadio/teatro donde ocurre', max_length=200, verbose_name='Nombre del lugar'),
        ),
    ]
