# Generated by Django 5.1.5 on 2025-10-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_add_ml_feature_extraction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='first_paragraph',
            field=models.TextField(blank=True, help_text='Extracto del primer párrafo para mostrar en UI (auto-generado)', verbose_name='Primer párrafo'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='business_relevance_score',
            field=models.FloatField(default=-1.0, help_text='-1.0 = no procesado, 0.0+ = procesado con score de relevancia', verbose_name='Puntuación de relevancia comercial'),
        ),
    ]
