# Generated by Django 5.1.5 on 2025-10-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsarticle_first_paragraph_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='news_newsar_is_proc_790ee4_idx',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='is_processed',
        ),
    ]
