# Generated by Django 5.1.5 on 2025-10-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_newsarticle_news_newsar_is_proc_790ee4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='colombian_involvement',
            field=models.BooleanField(default=False, help_text='True si el evento involucra a Colombia o colombianos (deportes, cultura, etc.)', verbose_name='Involucra a Colombia'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='event_country',
            field=models.CharField(blank=True, help_text='País donde ocurre físicamente el evento', max_length=100, verbose_name='País del evento'),
        ),
    ]
