# Generated by Django 5.1.5 on 2025-10-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_add_llm_extraction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='broadcastability_score',
            field=models.FloatField(default=0.0, help_text='0.0-1.0: Probabilidad de que el evento sea transmitido en TV y atraiga público a pubs', verbose_name='Puntuación de broadcastability'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='competition_level',
            field=models.CharField(blank=True, help_text='Nivel de competición: world_cup, champions_league, tour_de_france, etc.', max_length=100, verbose_name='Nivel de competición'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='hype_score',
            field=models.FloatField(default=0.0, help_text='0.0-1.0: Nivel de emoción/expectativa del evento (finales, clásicos, históricos)', verbose_name='Puntuación de hype'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_broadcastable',
            field=models.BooleanField(default=False, help_text='True si broadcastability_score >= umbral mínimo (relevante para negocios con TVs)', verbose_name='Es transmisible'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sport_type',
            field=models.CharField(blank=True, help_text='Deporte detectado: soccer, cycling, combat_sports, basketball, etc.', max_length=50, verbose_name='Tipo de deporte'),
        ),
    ]
