# Generated by Django 5.1.5 on 2025-10-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_add_broadcastability_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='cuisine_types',
            field=models.JSONField(blank=True, default=list, help_text='Lista de tipos de cocina detectados: ["italian", "japanese", "fusion"]', verbose_name='Tipos de cocina'),
        ),
    ]
