# Generated by Django 5.1.5 on 2025-10-27 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_add_cuisine_types_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlhistory',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_history', to='news.newssource', verbose_name='Fuente'),
        ),
    ]
