# Generated by Django 5.1.5 on 2025-10-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_businesstype'),
        ('news', '0014_alter_crawlhistory_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBusinessTypeRelevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(db_index=True, help_text='0.0-1.0: Qué tan relevante es este artículo para este tipo de negocio', verbose_name='Puntuación de relevancia')),
                ('suitability_component', models.FloatField(default=0.0, help_text='Contribución del business_suitability_score', verbose_name='Componente de idoneidad')),
                ('keyword_component', models.FloatField(default=0.0, help_text='Contribución del matching de keywords', verbose_name='Componente de palabras clave')),
                ('event_scale_component', models.FloatField(default=0.0, help_text='Contribución de la escala del evento', verbose_name='Componente de escala')),
                ('neighborhood_component', models.FloatField(default=0.0, help_text='Contribución de cercanía geográfica', verbose_name='Componente de proximidad')),
                ('matching_keywords', models.JSONField(blank=True, default=list, help_text='Lista de keywords que generaron matching para este tipo', verbose_name='Palabras clave que coincidieron')),
                ('calculated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Calculado el')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_relevance_scores', to='news.newsarticle', verbose_name='Artículo')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_scores', to='businesses.businesstype', verbose_name='Tipo de negocio')),
            ],
            options={
                'verbose_name': 'Relevancia artículo-tipo de negocio',
                'verbose_name_plural': 'Relevancias artículo-tipo de negocio',
                'ordering': ['-relevance_score'],
                'indexes': [models.Index(fields=['business_type', 'relevance_score'], name='news_articl_busines_bf7876_idx'), models.Index(fields=['article', 'business_type'], name='news_articl_article_becc4f_idx'), models.Index(fields=['-relevance_score'], name='news_articl_relevan_95da8f_idx')],
                'unique_together': {('article', 'business_type')},
            },
        ),
    ]
