# Generated by Django 5.1.5 on 2025-10-29 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_articlebusinesstyperelevance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='newsarticle',
            name='news_newsar_busines_9d5769_idx',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='business_relevance_score',
        ),
        migrations.RemoveField(
            model_name='socialmediapost',
            name='business_relevance_score',
        ),
    ]
